import LogoSearchCart from '@/components/Heading/LogoSearchCart/LogoSearchCart';
import Navbar from '@/components/Heading/Navbar/Navbar';
import TopBar from '@/components/Heading/TopBar/TopBar';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css'
          integrity='sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=='
          crossOrigin='anonymous'
          referrerPolicy='no-referrer'
        />
      </Head>
      <main>
        {/* -Heading-
          //TOPBAR          
          //LOGO | SEARCH | CART
          //NAV
         */}
        <TopBar />
        <LogoSearchCart />
        <Navbar />
        {/* Navbar */}
        {/* Three Collections */}
        {/* Carousel | New Products*/}
        {/* Hot Deal */}
        {/* Carousel | TOP SELLING*/}
        {/* Carousel | Multi */}
        {/* Sign up news */}
        {/* Footer */}
      </main>
    </>
  );
}
